version: '2.2'

services:
  web:
    build: ./front/
    image: sajt-app
    container_name: sajt-app-co
    restart: always
    command: >
      sh -c "npm run dev"
    ports:
      - "8080:8080"
  scrape: 
    build: ./scrape_fl/
    image: scrape-app
    container_name:  scrape-app-co
    restart: always
    command: > 
      sh -c "python fsfast.py"
    ports:
      - "4444:4444"